/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx}', './components/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:   { DEFAULT: '#185FA5', dark: '#0C447C', light: '#E6F1FB' },
        secondary: { DEFAULT: '#1D9E75', light: '#E6F5F0' },
        charcoal:  '#2C2C2A',
        success:   '#1D9E75',
        error:     '#D93025',
        warning:   '#F59E0B',
        border:    '#D1DCE8',
        surface:   '#FFFFFF',
        bg:        '#F4F8FC',
        ds: {
          bg:           'var(--ds-bg)',
          card:         'var(--ds-card)',
          border:       'var(--ds-border)',
          borderStrong: 'var(--ds-borderStrong)',
          inputBorder:  'var(--ds-inputBorder)',
          text:         'var(--ds-text)',
          textSecondary:'var(--ds-textSecondary)',
          textTertiary: 'var(--ds-textTertiary)',
          textMuted:    'var(--ds-textMuted)',
          success:      'var(--ds-success)',
          successLight: 'var(--ds-successLight)',
          warning:      'var(--ds-warning)',
          warningLight: 'var(--ds-warningLight)',
          danger:       'var(--ds-danger)',
          dangerLight:  'var(--ds-dangerLight)',
        },
      },
      fontFamily: {
        heading: ['Inter', 'system-ui', 'sans-serif'],
        body:    ['Inter', 'system-ui', 'sans-serif'],
        sans:    ['Inter', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        sm:      '4px',
        DEFAULT: '8px',
        lg:      '12px',
        xl:      '12px',
        '2xl':   '16px',
        btn:     '999px',
      },
      boxShadow: {
        sm:      '0 1px 2px rgba(12,68,124,0.06)',
        DEFAULT: '0 2px 8px rgba(12,68,124,0.10)',
        md:      '0 4px 16px rgba(12,68,124,0.12)',
        lg:      '0 8px 32px rgba(12,68,124,0.16)',
        xl:      '0 16px 48px rgba(12,68,124,0.20)',
      },
    },
  },
  plugins: [],
};
